service:
  name: mongo-express
  deployment:
    replicas: 1
    container:
      name: mongo-express
      image: mongo-express:latest
      containerPort: 8081
  data:
    env:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo-service:27017/?authSource=admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH: false
  ingress:
    data:
      host: mongo-express.beeyond.local
      path: /
      pathType: Prefix
      portNumber: 8081
  svc:
    type: ClusterIP
    port: 8081
    targetPort: 8081