# values : values passed into the template from the values.yaml file and from user-supplied files bu default values is empty
database:
  connectionString: mongodb://admin:admin@mongo-service:27017/abhishek?authSource=admin
backend:
  jwt_secret: super-secret-key-123
  port: '5000'
frontend:  
  frontend_Url: http://beyoond.frontend.local:30856