apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-web-app
  labels:
    app: mongo-app
  namespace: beeyond
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-express-webapp
        image: mongo-express:latest
        ports: 
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: ME_CONFIG_BASICAUTH
          value: "false"

