apiVersion: v1
data:
  .dockerconfigjson: <key>
kind: Secret
metadata:
  creationTimestamp: "2026-01-08T07:54:53Z"
  name: regcred
  namespace: beeyond
  resourceVersion: "7498"
  uid: 6236608a-7b79-4609-86ee-61e0fdb8d0e5
type: kubernetes.io/dockerconfigjson