apiVersion: v1
kind: PersistentVolume
metadata:
  name: beeyond-persistent-volume
spec:
  storageClassName: beeyond-volume
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/abhishek/Desktop/Beeyond
    type: DirectoryOrCreate