apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: beeyond
spec:
  type: ClusterIP
  selector:
    name: mongo
  ports:
    - port: 27017 
      targetPort: 27017
      name: mongo
      protocol: TCP