apiVersion: v1
kind: Service 
metadata:
  name: mongo-express-service
  namespace: beeyond
spec:
  type: NodePort
  selector:
    app: mongo-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30100

